version: '2'
services:
    simple-app:
        image: simple
        external_links:
            - simple-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/simple?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simple-mysql:
        extends:
            file: mysql.yml
            service: simple-mysql
